In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
from sklearn.metrics import precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from sklearn import metrics

import seaborn as sns

In [6]:
train = pd.read_csv('/Users/karthikprakasham/Desktop/High Volume Resource Files/creditcard.csv')

In [7]:
train

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [8]:
train['Class'].value_counts(normalize=True)

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

In [9]:
#Oversampling
#Undersampling
#Class imbalance Weighting
#Threshold tuning

In [10]:
X = train.drop('Class', axis=1)
y = train['Class']

In [11]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=24)
print(train_X.shape, test_X.shape, train_y.shape, test_y.shape)

(227845, 30) (56962, 30) (227845,) (56962,)


In [12]:
def Train_Fit_Report(model, train_X, train_y, test_X, test_y):
    model.fit(train_X, train_y)
    train_pred = model.predict(train_X)
    test_pred = model.predict(test_X)
    
    print("Train Accuracy:", accuracy_score(train_y, train_pred))
    print("Test Accuracy:", accuracy_score(test_y, test_pred))
    
    print("Train Classification Report:\n", classification_report(train_y, train_pred))
    print("Test Classification Report:\n", classification_report(test_y, test_pred))
    
    print("Train Confusion Matrix:\n", confusion_matrix(train_y, train_pred))
    print("Test Confusion Matrix:\n", confusion_matrix(test_y, test_pred))
    return model
    

In [13]:
#Home work.1 to do a GRID SEARCH CV for hyperparameter tuning
decisionTree_imbalanced = DecisionTreeClassifier()
Train_Fit_Report(decisionTree_imbalanced, train_X, train_y, test_X, test_y)

Train Accuracy: 1.0
Test Accuracy: 0.9988588883817282
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       1.00      1.00      1.00       376

    accuracy                           1.00    227845
   macro avg       1.00      1.00      1.00    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.72      0.72      0.72       116

    accuracy                           1.00     56962
   macro avg       0.86      0.86      0.86     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227469      0]
 [     0    376]]
Test Confusion Matrix:
 [[56813    33]
 [   32    84]]


DecisionTreeClassifier()

In [14]:
decisionTree_roughTuned = DecisionTreeClassifier(max_depth=5)
Train_Fit_Report(decisionTree_roughTuned, train_X, train_y, test_X, test_y)

Train Accuracy: 0.9996576620070662
Test Accuracy: 0.9991397773954567
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       0.95      0.84      0.89       376

    accuracy                           1.00    227845
   macro avg       0.97      0.92      0.94    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.85      0.70      0.77       116

    accuracy                           1.00     56962
   macro avg       0.93      0.85      0.88     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227451     18]
 [    60    316]]
Test Confusion Matrix:
 [[56832    14]
 [   35    81]]


DecisionTreeClassifier(max_depth=5)

## Random Forest Parameters
1. n_estimators --> How many trees you want to build
2. max_depth --> How deep each tree should be
3. min_samples_split --> Minimum samples required to split a node
4. min_samples_leaf --> Minimum samples required at each leaf node
5. max_features --> Number of features to consider at each split
6. criterion --> 'gini' or 'entropy' for classification
7. Class_weight --> 'balanced' to handle class imbalance, which mistakes in classification are more costly 
8. Bootstrap --> Whether to use bootstrap samples or not

In [15]:
# Home work.2 to add parameters for Random Forest Classifier
randomForest = RandomForestClassifier()
randomForest = Train_Fit_Report(randomForest, train_X, train_y, test_X, test_y)

Train Accuracy: 1.0
Test Accuracy: 0.9992275552122467
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       1.00      1.00      1.00       376

    accuracy                           1.00    227845
   macro avg       1.00      1.00      1.00    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.88      0.72      0.79       116

    accuracy                           1.00     56962
   macro avg       0.94      0.86      0.90     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227469      0]
 [     0    376]]
Test Confusion Matrix:
 [[56834    12]
 [   32    84]]


## Ada Boost Parameters:
1. n_estimators: How many corrective rounds should model perform
2. learning_rate: How strongly should each tree correct the previous mistakes / How much influence should each tree have when correct past mistakes.
3. base_estimator: 

In [16]:
adaBoost = AdaBoostClassifier(n_estimators=100, learning_rate=0.5)
adaBoost = Train_Fit_Report(adaBoost, train_X, train_y, test_X, test_y)

Train Accuracy: 0.9991222102745287
Test Accuracy: 0.9988764439450862
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       0.75      0.70      0.72       376

    accuracy                           1.00    227845
   macro avg       0.88      0.85      0.86    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.82      0.58      0.68       116

    accuracy                           1.00     56962
   macro avg       0.91      0.79      0.84     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227383     86]
 [   114    262]]
Test Confusion Matrix:
 [[56831    15]
 [   49    67]]


## Observations of AdaBoost:
1. High Learning Rate = Overfitting
2. Too Many estimators also include risk of overfitting

In [17]:
gbmBoost = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=24)
gbmBoost = Train_Fit_Report(gbmBoost, train_X, train_y, test_X, test_y)

Train Accuracy: 0.9990563760451184
Test Accuracy: 0.9985955549313578
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       0.84      0.53      0.65       376

    accuracy                           1.00    227845
   macro avg       0.92      0.77      0.82    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.79      0.42      0.55       116

    accuracy                           1.00     56962
   macro avg       0.89      0.71      0.77     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227430     39]
 [   176    200]]
Test Confusion Matrix:
 [[56833    13]
 [   67    49]]


Observations of Gradient Boost:
1. Slower than Randomforest
2. Careful tuning is very very important

## Parameters for XG Boost:
1. n_estimators - How many trees?
2. learning_rate - How fast do we learn?
3. max_depth - how complex is each tree?
4. subsample - How much data does each tree see?
5. colsample_bytree - How many features per tree?
6. reg_alpha & reg_lamda - How much do we punish complexity
7. scale_pos_weight - How much more important is fraud?
8. min_child_weight - How much data must a branch have to be not pruned?
9. gamma - IS this current split worth it? - forces you to have meaningful improvements only - Minimum benifit requrement.
10. colsample_bylevel - how man feature per tree level?

In [18]:
xgbBoost = XGBClassifier()
xgbBoost = Train_Fit_Report(xgbBoost, train_X, train_y, test_X, test_y)

Train Accuracy: 0.9999824442054905
Test Accuracy: 0.9992451107756047
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       1.00      0.99      0.99       376

    accuracy                           1.00    227845
   macro avg       1.00      0.99      1.00    227845
weighted avg       1.00      1.00      1.00    227845

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.88      0.72      0.80       116

    accuracy                           1.00     56962
   macro avg       0.94      0.86      0.90     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227469      0]
 [     4    372]]
Test Confusion Matrix:
 [[56835    11]
 [   32    84]]


## Observations of XG Extensive Gradient Boost:
1. Out of all ensemble models XGB performes best
2. XGB is prod version of GBM
3. Regularization (l1/l2)
4. Extreme pruing can be done via Gamma


In [19]:
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
scaler = StandardScaler()

X_scaled = pd.DataFrame(scaler.fit_transform(X),columns=X.columns)
train_X_scaled, test_X_scaled, train_y_scaled, test_y_scaled = train_test_split(X_scaled, y, test_size=0.2, random_state=24)


In [20]:
randomSampler = RandomOverSampler(random_state=24)
X_resampled, y_resampled = randomSampler.fit_resample(train_X_scaled, train_y_scaled)

print(train_y_scaled.value_counts())
print(y_resampled.value_counts())

Class
0    227469
1       376
Name: count, dtype: int64
Class
0    227469
1    227469
Name: count, dtype: int64


In [21]:
print("After Scaling and Resampling")
print("-----------------------------------------------------------------")
print("Decision Tree Classifier Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(decisionTree_imbalanced, X_resampled, y_resampled, test_X_scaled, test_y_scaled)
print("-----------------------------------------------------------------")
print("Decision Tree Classifier Rougn Tuned Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(decisionTree_roughTuned, X_resampled, y_resampled, test_X_scaled, test_y_scaled)
print("-----------------------------------------------------------------")
print("Random Forest Classifier Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(randomForest, X_resampled, y_resampled, test_X_scaled, test_y_scaled)
print("-----------------------------------------------------------------")
print("Ada Boost Classifier Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(adaBoost, X_resampled, y_resampled, test_X_scaled, test_y_scaled)
print("-----------------------------------------------------------------")
print("Gradient Boosting Classifier Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(gbmBoost, X_resampled, y_resampled, test_X_scaled, test_y_scaled)
print("-----------------------------------------------------------------")
print("XG Boost Classifier Results")
print("-----------------------------------------------------------------")
Train_Fit_Report(xgbBoost, X_resampled, y_resampled, test_X_scaled, test_y_scaled)

After Scaling and Resampling
-----------------------------------------------------------------
Decision Tree Classifier Results
-----------------------------------------------------------------
Train Accuracy: 1.0
Test Accuracy: 0.9990168884519505
Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    227469
           1       1.00      1.00      1.00    227469

    accuracy                           1.00    454938
   macro avg       1.00      1.00      1.00    454938
weighted avg       1.00      1.00      1.00    454938

Test Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56846
           1       0.79      0.70      0.74       116

    accuracy                           1.00     56962
   macro avg       0.90      0.85      0.87     56962
weighted avg       1.00      1.00      1.00     56962

Train Confusion Matrix:
 [[227469      

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)